### ISSUE TITLE
Ubuntu 16.10 amd64 segfault 

### ISSUE THREAD

**Issue by dagheyman** [Yubico/yubioath-desktop#139]
From the mailing list on launchpad:
> Since the update to version 4.0.0 yubioath-desktop doesn't start and
throws a Segmentation Fault exception, on all my amd64 based ubuntu
16.10 computers. Please fix this.

**Comment by ilya40umov** [comment]
+1
Same thing on Linux Mint 18.1.
I'm gonna have to install a previous version manually for now.

**Comment by dagheyman** [comment]
My guess is this is some kind of bug with the Qt5 version in Ubuntu 16.10 in combination with Unity.

Confirmed working:
16.04 + Unity
16.10 + Gnome 3
17.04 Beta 2 + Unity

Confirmed crashing:
16.10 + Unity

**Comment by dagheyman** [comment]
From syslog: `yubioath-desktop[4391]: segfault at 0 ip 00007efc5a7a6c7f sp 00007ffdb8a99c00 error 4 in libQt5XcbQpa.so.5.6.1[7efc5a705000+fb000]`

This project https://github.com/Ultimaker/Cura/issues/1094 seems to have a similar issue with libQt5XcbQpa.so.5.6.1. on Ubuntu 16.10

**Comment by lilianmoraru** [comment]
You can read these 2 comments: https://github.com/Ultimaker/Cura/issues/1094#issuecomment-257858271 and the next one https://github.com/Ultimaker/Cura/issues/1094#issuecomment-257923227
In that issue, `dbusmenu` seems to be at fault.

**Comment by dagheyman** [comment]
Possibly related to [QTBUG-55966](https://bugreports.qt.io/browse/QTBUG-55966) which seems to be fixed in Qt 5.6.3. 

Not sure what a good workaround would be for Ubuntu 16.10

**Comment by dmaroulidis** [comment]
Actually I tested this on Ubuntu Gnome 16.10 + Gnome 3 amd64 and it's crashing, and I sent that report.

**Comment by dagheyman** [comment]
> Actually I tested this on Ubuntu Gnome 16.10 + Gnome 3 amd64 and it's crashing, and I sent that report.

Thanks for the initial report and good that you found this issue thread. I just tested on a fresh install of Ubuntu GNOME 16.10 64bit but it seems to work in my VM at least.

![screen shot 2017-03-28 at 14 45 18](https://cloud.githubusercontent.com/assets/9592259/24405502/627f37b6-13c5-11e7-9b40-4f0cc3557805.png)

**Comment by ilya40umov** [comment]
In my case it's Linux Mint 18.1 64-bit with Cinnamon.
I've again reinstalled the new version of "yubioath-desktop" and it won't start.
I would love to provide more info but I have no idea where to look for it.

**Comment by ilya40umov** [comment]
Please, ignore my previous comments about Linux Mint 18.1 64-bit with Cinnamon. It actually works, I just needed to reboot the system.

**Comment by dmaroulidis** [comment]
Ok, so maybe something else happened since my installation of Ubuntu Gnome 16.10 64bit. Does your VM have all the latest updates installed?

**Comment by dmaroulidis** [comment]
I see that this problem is now solved. I think that was through updates.

**Comment by nshtg** [comment]
I still have this problem on kubuntu 17.04. so I guess it's not really fixed?

The client works and asks for the code after that it crashes with a segfault error.

**Comment by dagheyman** [comment]
@nshtg Thanks for the report, I was able to reproduce it on 17.04. But it seems to be a different error, so I opened a new issue for it: #160

**Comment by mattdoiron** [comment]
I also have this issue on Ubuntu 16.10

`yubioath-deskto[12449]: segfault at 0 ip 00007f4d61fafc7f sp 00007ffe18e547a0 error 4 in libQt5XcbQpa.so.5.6.1[7f4d61f0e000+fb000]`

**Comment by minisu** [comment]
Was broken for me in Ubuntu 16.10. Now works in 17.04.

**Comment by dagheyman** [comment]
Will not be fixed since [Ubuntu 16.10 is end of life](https://lists.ubuntu.com/archives/ubuntu-announce/2017-July/000223.html).
