### ISSUE TITLE
Fails to read unless ran as administrator

### ISSUE THREAD

**Issue by jou-calvin** [Yubico/yubioath-desktop#368]
- Yubico Authenticator version: 4.3.5
- Operating system and version: Windows 10 1903, Build 18362.86
- YubiKey model and version: YubiKey Neo OTP+U2F+CCID
- Bug description summary: The Windows 10 2019 May update has introduced changes to natively provide a UI during U2F challenges in browsers. I believe these changes might have affected how Windows interact with YubiKeys. When the Authenticator is opened normally, I get the message `Authenticator mode is set to CCID, but the CCID connection is not enabled` despite having CCID enabled. A workaround is to run the program as administrator. 

Steps to reproduce
Enroll in the Windows Insiders Program and choose just fixes, apps, and drivers
Open the Authenticator app with key inserted.

I have verified that the key functions with Authenticator over NFC and USB through an OTG adapter on my Android phone, and have been able to reproduce this behavior on two Windows 10 1903 computers.

**Comment by dagheyman** [comment]
Thanks for the report, will look into it. We're aware of the changes coming to Windows, but it shouldn't effect the CCID interface, which this app is mainly using.

**Comment by dagheyman** [comment]
This seems fixed in build 18362.113, could you verify?

**Comment by jou-calvin** [comment]
It appears on both of my computers on 18362.113 that I am still getting the error. 

When running `ykman oath` without admin I am also able to replicate your log output:

```Traceback (most recent call last):

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\driver_ccid.py", line 225, in send_apdu
    resp, sw1, sw2 = self._conn.transmit(header + body)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\smartcard\CardConnectionDecorator.py", line 82, in transmit
    return self.component.transmit(bytes, protocol)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\smartcard\CardConnection.py", line 146, in transmit
    data, sw1, sw2 = self.doTransmit(bytes, protocol)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\smartcard\pcsc\PCSCCardConnection.py", line 205, in doTransmit
    SCardGetErrorMessage(hresult))

smartcard.Exceptions.CardConnectionException: Failed to transmit with protocol T1. Access is denied to this file.```

**Comment by dagheyman** [comment]
You are correct, tried again and the problem doesn't seem to be fixed. I must have mixed something up.

**Comment by kristankenney** [comment]
I can confirm this issue is still present on Windows 10 build 18362.116 with a Yubikey Neo.

**Comment by dagheyman** [comment]
This should now work with Yubico Authenticator 4.3.6

**Comment by kristankenney** [comment]
Working as expected now, thanks for getting this fixed up. :)
