### ISSUE TITLE
Weird problems on startup/wake from sleep on OS X + Linux

### ISSUE THREAD

**Issue by endophage** [Yubico/yubioath-desktop#69]
The app seems to get into a weird state when started during boot or resuming from sleep. It generates an invalid code, the timer doesn't start, and it refuses to generate any other codes. I have to shut down the app and restart to get it working again. It's a minor annoyance and I'll dig into it if and when I have time, just filing this in case somebody else has time sooner.

System info:
```
$ uname -a
Linux endophage 4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 08:12:23 CET 2016 x86_64 GNU/Linux
$ pacman -Qs yubico-yubioath-desktop
local/yubico-yubioath-desktop 2.3.0-1
    Crossplatform graphical user interface to generate one-time passwords.
```

Screenshot of app state when broken:
![yubioath](https://cloud.githubusercontent.com/assets/1302091/12857377/bd962444-cbfe-11e5-9f83-1eaed811fee9.png)

Note no timer running and the button to generate a new code is disabled. The displayed code does not work when logging in to the configured service. On restarting the app, a working code is correctly generated and the timer runs.

**Comment by xortim** [comment]
I can confirm similar behavior on OS X

**Comment by jskvbinmv** [comment]
Just happened to me on Ubuntu 15.10

**Comment by dagheyman** [comment]
I'm having a hard time reproducing this, for me it seems to work fine to go in and out of sleep as well on starting the program during boot. If someone have the possibility to provide logs from running the program from the command line when having the program in this state it would help a lot.

**Comment by endophage** [comment]
Retested (on OSX) with @a-dma and @klali looking looking over my shoulder and it seems to have been fixed since February. 

@xortim are you still able to repo on OSX with the latest version?

@jskvbinmv are you able to confirm whether it's fixed or still breaking on Linux?

**Comment by xortim** [comment]
@endophage - I worked around the problem by writing a ControlPlane context to kill the app when I unplug my key.

**Comment by bwalding** [comment]
This is still occurring every day (for me) on 3.1.0 on OSX 10.12 - if you can suggest a way to cause the app to crash out and generate something useful - then I'm happy to do that.

I tried a `kill -SEGV pid` - and it has generated a report - but I'm wary about posting it publicly without sanitisation.

**Comment by dagheyman** [comment]
> This is still occurring every day (for me) on 3.1.0 on OSX 10.12 - if you can suggest a way to cause the app to crash out and generate something useful - then I'm happy to do that.

Could you see if the issue is still there with the 4.0.1 version?

**Comment by bwalding** [comment]
I thought I had checked for a newer version - but apparently not!

I've installed the newer version and will leave it running and see what happens.
